### ISSUE TITLE
Registration Date Vs Confirmation Date

### ISSUE THREAD

**Issue by leomontano** [bramley/phplist-plugin-autoresponder#1]
Congratulations on this plugin, just that I have an observation, sending the autoresponder starts from the date the registration email. I think that sending autoresponder should be from confirmation as this may be two or more days following registration. if the person currently confirmed three days after the registration and there autoresponder to send the day 1, 2 and 3, are sent together.

**Comment by bramley** [comment]
Your suggestion makes sense but currently phplist doesn't seem to record when the person confirms the subscription, only when the initial subscription is made.
