### ISSUE TITLE
FR: Action on List Completion

### ISSUE THREAD

**Issue by justinputney** [bramley/phplist-plugin-autoresponder#2]
Hi,

This looks exactly like what I've been looking for for months. I have 1 feature request and 1 suggestion.

FR: I'd love to be able to add/copy a subscriber to my main list after they've received all of the AutoResponder emails. Is it possible to add something like this?

Suggestion: This seems like a super useful plugin, but I didn't know to look for it. I was search for "drip" because this type of autoresponding is also known as "drip marketing." If you add this text to your plugin description, you will probably get a lot more page views and downloads, FWIW.

**Comment by justinputney** [comment]
Hi Duncan,
I've sent a donation your way as a thank you for all your awesome plugins!

Here's a little more detail on my feature request (a mockup of how I would hope it would work):
![drip complete](https://cloud.githubusercontent.com/assets/1245892/8515939/3b7f5d5e-2361-11e5-9231-e116fd23dbb9.png)

Or here's another approach:
![drip complete 2](https://cloud.githubusercontent.com/assets/1245892/8516002/751d9bf6-2362-11e5-8549-4321ba776f5b.png)

I'd be happy to send another donation your way if you can make this feature happen. ;)

I'm also happy to promote this and your other plugins. Based on your awesome work, you're also the first person I would contact or recommend for phplist plugin development. Thanks!

**Comment by bramley** [comment]
I have added a simplified form of this. You can select a list to which each subscriber will be added when the autoresponder campaign has been sent to them.

![screenshot](https://cloud.githubusercontent.com/assets/3147688/8980350/bf0b1b78-36a7-11e5-8f1b-8149b27513a9.png)

**Comment by justinputney** [comment]
Awesome! Can't wait to try it.

**Comment by bramley** [comment]
I have just noticed that there is a bug in the plugin code that I released earlier, it does not add the user to the list when the campaign has been sent.
 I have now fixed that and the latest plugin code works correctly.

**Comment by justinputney** [comment]
Thanks for catching this, Duncan. I haven't had a chance to test it yet (I'm still writing the campaigns), but I will test the update soon.

**Comment by leomontano** [comment]
![errorautoresponder](https://cloud.githubusercontent.com/assets/11681487/9140076/a2418730-3ceb-11e5-99b2-584940bf4f47.PNG)

Hi

I update the plugin autoresponder and run "manage autoresponder" option sends the following error:

---

Sorry a software error occurred:
Please report a bug when reporting the bug, please include URL and the entire content of this page.

Fatal error: Class 'CHtml' not found in /home4/montano/public_html/subliminalx.biz/lists/admin/plugins/Autoresponder/Controller.php on line 113

## phpList version 3.0.12

You can help ?

Thanks

Leo Montaño

**Comment by bramley** [comment]
You now need to install my Common Plugin with the Autoresponder plugin. Please see the installation instructions for that.
In the next release of phplist there will be some validation of plugin dependencies that should help to avoid this problem.

**Comment by leomontano** [comment]
Perfect, thank you, I solved the problem

**Comment by leomontano** [comment]
emails in the second list will be sent after the last post of the first list is sent?
