### ISSUE TITLE
FR: Filter by Campaign

### ISSUE THREAD

**Issue by justinputney** [bramley/phplist-plugin-autoresponder#4]
As I'm putting together my list of autoresponder emails, I'm realizing the list will be quite long. It would be really useful to filter by campaign.

**Comment by bramley** [comment]
Do you mean filtering (limiting which autoresponders are actually listed) or ordering?
If you want to list the autoresponders in the order that they would be sent then that would be ordering by the delay period.
Possibly adding a field, sequence, which can be anything you like, and then ordering by that might be most flexible.

**Comment by justinputney** [comment]
Limiting the messages that are listed on the page by the list that they are associated with.

That way you can look at the autoresponders associated with a single list (e.g. list 1, list 2, free email course, etc).
I'm currently planning a course that will be over 12 emails by itself.

Within each list, I still want to view the messages in the order they will be sent.

**Comment by bramley** [comment]
The latest release includes filtering by list.

**Comment by justinputney** [comment]
Thanks, Duncan! Looks great!
