### ISSUE TITLE
Empty page.

### ISSUE THREAD

**Issue by fikko2** [bramley/phplist-plugin-autoresponder#6]
Dear sir,

I just install the plugin with my phplist 3.0.12, and enable the autoresponder.

The menu is coming out. There is a manage & process Autoresponder, but the screen Is just empty. I guess the problem is somewhere around manage.php.

![help](https://cloud.githubusercontent.com/assets/13848413/9326595/0f8a6aaa-45c5-11e5-907a-d6ae3fee180a.PNG)

see this: 
echo("Hello");
CommonPlugin_Main::run(new Autoresponder_ControllerFactory);

I am not too good at programming...

I am very pleased if you can let me know what to do.

Thanks.

Fikko

**Comment by bramley** [comment]
Have you also installed the CommonPlugin as mentioned in the installation instructions?

**Comment by fikko2** [comment]
You are right... I haven't installed it yet...
I will do. Thank you. You are awesome.

**Comment by fikko2** [comment]
Hi Mr. Bramley,

The auto responder is working after I add common plugin. Thank you very much. My website is now working.
http://www.shopthings.com
http://www.shopthings.com/lists/

Thanks for your awesome Autoresponder and help.
