### ISSUE TITLE
Sending mail based on date from attribute

### ISSUE THREAD

**Issue by jobefp** [bramley/phplist-plugin-autoresponder#7]
Hi, would it be possible to extend functionality to send e-mail not based on when user joined, but based on date from user atrribute? This date could be e.g. date of birtday. Thank you.

**Comment by bramley** [comment]
I'm not sure that I understand what you are asking for.
If the date attribute was a date of birth with a value of say "10 June 1985" how would the plugin decide whether to send the campaign to that subscriber?
The Segment plugin https://github.com/bramley/phplist-plugin-segment handles sending campaigns based on subscriber attributes so you might want to look at that.

**Comment by jobefp** [comment]
Hi, in attribute I would use date of birthday, e.g. "10 June 2015", not date of birth "... 1985". When I compare to segment plugin I like autoresponder more, because compain can be send from cron.

**Comment by bramley** [comment]
You can use the Segment plugin to create a simple autoresponder for a date attribute.  Use the "after interval" operator to select subscribers whose attribute value is the specified number of days before the current date.

On the Schedule tab set the campaign to requeue every day and set the embargo time to be the time of day that you want it to be sent.
Use  a cron job that runs at least once a day just after the embargo time to process the queue.

**Comment by jobefp** [comment]
Perfect! Thank you.
