### ISSUE TITLE
Call to undefined method phpList\plugin\Autoresponder\DAO::submitCampaign()

### ISSUE THREAD

**Issue by cefels** [bramley/phplist-plugin-autoresponder#9]
Hi Duncan & team!

I'm using PhpList version 3.5.5 with Php 7.4 and got this error after updating from Autoresponder 3.2.1 to 3.3.0 or 3.3.1: 

PHPlist - phpList version 3.5.5 (c) 2000-2020 phpList Ltd, https://www.phplist.com
PHP Fatal error:  Uncaught Error: Call to undefined method phpList\plugin\Autoresponder\DAO::submitCampaign() in /newsletter/lists/admin/plugins/Autoresponder.php:104
Stack trace:
#0 /newsletter/lists/admin/actions/processqueue.php(66): Autoresponder->processQueueStart()
#1 /newsletter/lists/admin/processqueue.php(22): include('/home/xxx/...')
#2 /newsletter/lists/admin/index.php(757): include('/home/xxx/...')
#3 {main}

I guess it was introduced due to this change:

https://github.com/bramley/phplist-plugin-autoresponder/commit/e45b34bc7ad0a0230cc0ac62a454dcd6dd9725dc#diff-c3c301fe7325afb66cffe1459a7a8911

Any ideas how to fix it? Thanks guys!

**Comment by bramley** [comment]
It looks like the Common Plugin is not up to date, it needs to be 3.12.2 or later.
If you look at the Manage Plugins page, is the Autoresponder plugin enabled? It should be disabled if Common Plugin is not up to date.

**Comment by cefels** [comment]
Thanks for your quick reply. 

Common Plugin is up to date (version 3.13.1). If I update Autoresponder from 3.2.1 to 3.3.0 (or 3.3.1) it appears as Enabled in Manage Plugins page but it not only doesn't send emails but also it makes the processqueue.php crash/fail so I cannot send campaigns either.

**Comment by bramley** [comment]
Are you updating the plugin using the Manage Plugins page, or manually?
Please check the file plugins/AutoresponderPlugin/DAO line 14 should be

```
namespace phpList\plugin\Autoresponder;

use phpList\plugin\Common;
use phpList\plugin\Common\DAO\MessageTrait;

```

You can temporarily disable the autoresponder plugin in order to be able to send other campaigns.

**Comment by cefels** [comment]
I updated it via Manage Plugins page but as it didn't work I then downgraded it manually. 

In both versions (3.2.1 in Production and 3.3.1 in Staging) the plugins/AutoresponderPlugin/DAO line 14 (16 & 17) looks as you said. 

Yes, I was disabling the Autoresponder plugin to send the campaigns. Thanks for the tip, it took me a while to figure it out because I updated Phplist from 3.5.2 to 3.5.5 on the same day that I updated the plugin so I didn't know which one was causing the problem.

Please let me know if you need further details.

**Comment by bramley** [comment]
The failure happens when running a cron job. Are you able to see whether the same happens when processing the queue through the browser? I wonder whether the web server and command line have a difference in their configurations.

**Comment by cefels** [comment]
I'm using Docker (regular phpList version not phplist-docker image) and I process the queue via cron job / command line doing:

/usr/bin/php7.4 /home/xxx/application/newsletter/lists/admin/index.php -pprocessqueue -c/home/xxx/application/newsletter/lists/config/config.php

When I process via browser it keeps saying processing and I can see a 500 error via Devtools and not further info in the logs.

**Comment by bramley** [comment]
Can you look at file plugins/Common/DAO/MessageTrait.php for the method submitCampaign() at the end of the file. I guess that it is not there, so if not then re-install Common Plugin on the Manage Plugins page.

**Comment by cefels** [comment]
You nailed it! That method was missing from plugins/Common/DAO/MessageTrait.php (who knows why!). I re-installed Common Plugin and update Autoresponder to 3.3.1 and everything is working like a charm. Thanks a lot for your help Duncan. 

Ps: Is there any project that I can contribute to or personal account to buy you a beer/coffee? Better if it is BTC or crypto account.
